# Generated by Django 4.1.7 on 2023-04-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_texto_disponible_alter_texto_edicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto',
            name='imagen',
        ),
    ]
