# Generated by Django 4.1.7 on 2023-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_texto_tapalibro_alter_texto_titulolibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='tapaLibro',
            field=models.ImageField(blank=True, default='libroblanco.jpg', null=True, upload_to='portada'),
        ),
    ]
