# Generated by Django 4.1.7 on 2023-04-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_texto_tapalibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='tapaLibro',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='portada/'),
        ),
    ]
